Codesweeper
uashogeschoolutrecht/sean pull request #14
Opened 2022-11-22 13:58 UTC by ALeemans

Alle overbodige functies en scripts verwijderd of naar de repo python-definitions verplats. 
Inlezen van bestanden uit topdesk als in aparte map
Validation in aparte map
User-app in aparte map

2022-11-22 14:52 UTC, Fraukje commented
Nice! Twee dingen:
- Bij mij bestaat de map python-scripts nog, maar met alleen maar .pyc bestanden. Weggooien?
- Map topdesk vind ik beter passen onder 'validation', eens?

2022-11-22 14:52 UTC, Fraukje requested changes
Two minor changes, see comment above

2022-11-22 15:38 UTC, ALeemans commented
ja goeie, je kan het argument maken dat je op een later moment ook email threads als input voor de app wil hebben maar voor nu on validation prima!

.pyc is denk ik een locale file en wordt uitgesloten via de gitignore kan weg ja

2022-11-23 07:57 UTC, ALeemans commented
aanpassing gedaan kan jij m goedkeuren/mergen?

2022-11-28 10:00 UTC, Fraukje approved these changes
ok

2022-11-28 10:00 UTC, merged